### ISSUE TITLE
TP= attribute parameter not parsed in the ST2110 SDP

### ISSUE THREAD

**Issue by ilansmith** [Streampunk/sdpoker#2]
TP= is a required attribute parameter as stated in 2110-21, section 8.1.

Need to add 'tp' to the mustHave array in checkST2110.js and handle it's parsing.

**Comment by sparkpunkd** [comment]
Thanks for pointing this out. I set out to build a tool to test the parameters of ST 2110-10,20 and 30. Indeed, I had not spotted that ST 2110-21 had now been published - but it has and the parameter is present.

For me, the question is what to do if you don't conform to ST 2110-21 - I know the streams my software produces do not but some other receivers with sufficient buffers are happy to receive them (audio and lower bit rate video). 

Perhaps add a command line flag `st2110-21` that, when set, checks the -21 specific parameters?

**Comment by ilansmith** [comment]
If your SDP includes an `m=video` clause for 2110 (i.e. it includes an `a=rtpmap:XXX raw/90000` attribute and an `a=fmtp:XXX` with parameter `SSN=ST2110-20`, it must also include a `TP=` parameter for the sender type since there's no default type defined. Failing to do so would render the receiving parameters undefined.
It's up to the receiver to ignore that if they want to I guess, but from a syntax point of view, it should  be present else it’s incomplete.

2110-21 does specify:
**8 Session Description Considerations 
8.1 Required Parameters** 
Senders **shall** include the following additional payload-format-specific Media Type parameters in the a=fmtp clause of the SDP for all video RTP streams conforming to this standard. 
`TP` Signals the type of the sender as defined in section 7.1. See section 7.1 for permitted values of this parameter under this standard.

**Comment by sparkpunkd** [comment]
Latest commit (v0.0.12) has an option `shaping` that, when enabled, checks that TP is present and that TROFF and CMAX have appropriate values.
