### ISSUE TITLE
ts-refclk:ptp=IEEE1588-2008:traceable

### ISSUE THREAD

**Issue by garethsb** [Streampunk/sdpoker#3]
I'm not convinced the checking of the ts-refclk attribute is quite right in checkST2110.js.

I think the following is correct to describe traceable PTP according to the ABNF in [RFC7273](https://tools.ietf.org/html/rfc7273#section-4.8)?

```
a=ts-refclk:ptp=IEEE1588-2008:traceable
```

**Comment by sparkpunkd** [comment]
I agree. Unfortunately, that means that SMPTE ST 2110-10:2017 Section 8.2 is wrong as it reads ...

    a=ts-refclk:ptp=traceable

My reading of the ABNF is that omitting the `ptp-version` part, e.g. `IEEE1588-2008`, is wrong?

Should SDPoker be updated to match the RFC or support the SMPTE example or both?

**Comment by garethsb** [comment]
I agree with your reading of the ABNF. I guess the mistake in ST 2110-10:2017 Section 8.2 needs raising with the powers that be… Sigh.

**Comment by garethsb** [comment]
Hi Richard. I have been informed this is already fixed in the draft 1-year review of ST 2110-10.

**Comment by sparkpunkd** [comment]
I've attempted to address this in commit f91cfeb6250c46c240b310081f864a326d7f05c3 and I'll close and publish by the end of the week if I get no further comment.

**Comment by sparkpunkd** [comment]
No further chat. Closing.
