### ISSUE TITLE
Ancillary not supported.

### ISSUE THREAD

**Issue by pkeroulas** [Streampunk/sdpoker#6]
Hello Richard,
Is there a plan to cover ST2110-40?
Thanks,
PK

**Comment by sparkpunkd** [comment]
No plan. Open to forks and pull requests. 

I don't have a copy of ST2110-40 and we're not working on ST2110 or NMOS at this time unless the activity is sponsored.

**Comment by pkeroulas** [comment]
Understood.
The actual issue is that SDPoker is confused by "m=video" which also applies to ancillary data (https://tools.ietf.org/id/draft-ietf-payload-rtp-ancillary-10.xml#n-sdp-considerations). I assume the rational was that ancillary is embedded in video signal in the SDI world. 

The result is false positives because video tests are performed over ancillary description for which "fmtp" and "rtpmap" rules are different.
 
PR#7 should fix it.

**Comment by pkeroulas** [comment]
@sparkpunkd, did you have a chance to look at the [PR](https://github.com/Streampunk/sdpoker/pull/7) ? It basically fixes the false positive on ancillary.

**Comment by sparkpunkd** [comment]
Just merged. Thanks for looking into this and providing the fix.
